### ISSUE TITLE
LAB vs REST display

### ISSUE THREAD

**Issue by npfoss** [npfoss/courseroad2#150]
Why does the rest requirement have a progress bar? (Seems like it should be the same as lab, which doesn't.)

**Comment by georgiashay** [comment]
The reason for this is that for LAB, the entire requirement is just GIR:LAB.  For REST, the requirement is GIR:REST with a threshold of >= 2.  So, it treats GIR:LAB as just a regular requirement because it looks no different than a regular class requirement.  REST is different because you're supposed to have multiple of them, so the progress bar is a way to know if you have completed 1/2 or 2/2. 
 
I can definitely see how this could be confusing.   One thing we could do is instead of a progress bar have two discrete boxes underneath it (or n in the general case) with them filled in (green or darker gray?) when they are completed.  That way it doesn't look the same as a higher-level requirement while still indicating that multiple things have to be completed.  The HASS requirement is also affected by this, for example.

**Comment by npfoss** [comment]
oh right gotcha.... ok that's fine, punting to backburner
